name = "dev-env"

[[tasks]]
type = "package"
packages = ["fish", "tmux", "starship"]

[[tasks]]
type = "template"
templates = [
  { src = "fish/config.fish.j2", dest = "{{ config_dir }}/fish/config.fish" },
  { src = "tmux/tmux.conf.j2", dest = "~/.tmux.conf" }
  { src = "starfish/starship.toml", dest = "{{ config_dir }}/starship.toml" }
]
