

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_grey2 fg:color_orange)\
$directory\
[](fg:color_grey2 bg:color_grey3)\
$git_branch\
$git_status\
[](fg:color_grey3 bg:color_grey4)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_grey4 bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_grey2 = '#928374'
color_grey3 = '#7c6f64'
color_grey4 = '#504945'
color_orange = '#d65d0e'
color_green = '#98971a'
color_red = '#cc241d'
color_yellow = '#d79921'
color_purple = '#b16286'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_grey2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_grey3"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_grey3)]($style)'

[git_status]
style = "bg:color_grey3"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_grey3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[c]
symbol = " "
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[rust]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[golang]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[php]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[java]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[kotlin]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[haskell]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[python]
symbol = ""
style = "bg:color_grey4"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_grey4)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[->](bold fg:color_green)'
error_symbol = '[->](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
